### ISSUE TITLE
Project is throwing an error when used in Twilio CLI Plugin

### ISSUE THREAD

**Issue by dkundel** [twilio-labs/create-twilio-function#15]
If you install the latest version (`create-twilio-function@next`) and try to use it in the plugin via `twilio serverless:init` it will create the directory and then throw an error that it exists.

Steps to repo:
1. clone the plugin repo (https://github.com/twilio-labs/plugin-serverless)
2. `cd plugin-serverless && npm install && npm install create-twilio-function@next`
3. `twilio plugin:link .`
4. in a different directory `twilio serverless:init pineapple`

If you instead locally clone `create-twilio-function` and change the step 2 to  `npm install ../create-twilio-function` instead it will work.

**Comment by philnash** [comment]
I had forgotten to include the `templates` directory in the `files` array in `package.json`.

🤦‍♂ 

This is fixed in version [`2.0.0-alpha.4`](https://www.npmjs.com/package/create-twilio-function/v/2.0.0-alpha.4).
