### ISSUE TITLE
Add a "npm run deploy" command

### ISSUE THREAD

**Issue by dkundel** [twilio-labs/create-twilio-function#21]
It would be nice if we could have instructions for Serverless projects like:

```bash
git clone ...
cd project
npm install
cp .env.example .env
# Add credentials to .env
npm run deploy
```

**Comment by philnash** [comment]
Should there be npm scripts for the other things `twilio-run` can do?

**Comment by dkundel** [comment]
Not right now. Btw you can drop --env from start. 2.0 introduced it as default

**Comment by philnash** [comment]
Ah, brilliant. Will add (well, remove) that too.
