### ISSUE TITLE
Use fixed window size if it is not available

### ISSUE THREAD

**Issue by philnash** [twilio-labs/create-twilio-function#24]
This package uses the `window-size` module to make sure the success message formats correctly based on the window size of the user's terminal.

Like in [twilio-run/#82](https://github.com/twilio-labs/twilio-run/issues/82), it could break if the `window-size` module cannot return a width and height.

We should default to a fixed width of, say, 80 in the case where `window-size` doesn't return a value.

Steps to implement:

* Create a new file in `src/create-twilio-function` called `window-size.js`
* implement a `get` function that returns either the object that the `window-size` module would return or a default of `{ width: 80, height: 300 }` (including tests)
* replace the use of `window-size` in `success-message.js` with this new module

**Comment by whitneyrosenberg** [comment]
Would it be alright if I took this task?

**Comment by philnash** [comment]
@whitneyrosenberg go for it!

**Comment by philnash** [comment]
Closed by #25 .
