### ISSUE TITLE
Add eslint to the project?

### ISSUE THREAD

**Issue by dlemstra** [twilio-labs/create-twilio-function#32]
Would this project be interested in having `eslint` added?

**Comment by philnash** [comment]
In theory, yes! @dkundel do you have an eslint config that we're using across Twilio Labs?

**Comment by dkundel** [comment]
Just commented on the PR. @ahcai is working on a general Twilio ESLint config. It's already on npm but not public yet. I think it would make sense to introduce it. https://npm.im/eslint-config-twilio

**Comment by dlemstra** [comment]
Gave the config from @ahcai a try and I got a lot of `Expected linebreaks to be 'LF' but found 'CRLF'   linebreak-style` errors. For people that work on Windows this will probably be an issue so maybe all the projects need a `.gitattributes` file? I also noticed that one of the things reported resulted in a warning (`Expected a function expression`) and I wonder if that should be changed into an error? Is there still some internal debate about the rules or can I go ahead and make the changes for the errors that are reported?

**Comment by dkundel** [comment]
@dlemstra good catches. Could you file an issue for this with github.com/twilio-labs/twilio-style? The repo is now public

**Comment by dlemstra** [comment]
Created two issues for this. Can I go ahead and fix the other problems that are reported?

**Comment by dkundel** [comment]
Yeah I think once those issues are fixed in the ESLint config I think it's the one we should pick

**Comment by philnash** [comment]
Can we update this PR to use the Twilio style config while we wait for the issues to be fixed there?

**Comment by dlemstra** [comment]
Just pushed a new commit to use the new configuration.

**Comment by philnash** [comment]
And we're all merged with this!
