### ISSUE TITLE
Update node version

### ISSUE THREAD

**Issue by philnash** [twilio-labs/create-twilio-function#48]
The underlying platform continues to update the version of Node 10 that functions uses. We should try to keep up to date somehow.

Is it ok to change [the version](https://github.com/twilio-labs/create-twilio-function/blob/master/src/create-twilio-function/versions.js#L3) to "10"? Or should we keep up to date to ensure the absolute latest?

**Comment by dkundel** [comment]
I think 10 is fine. Since 10 is an LTS release it should not have any breaking changes in minors

**Comment by philnash** [comment]
Good point, will relax it a bit more.
